name: CI/CD Build

on:
  #push:
  #  branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

  runs-on: ubuntu-latest
  variables:
    version: format('yyyy.MM.dd',pipeline.startTime)
    
  steps:
  - name: Setup NuGet.exe for use with actions
    uses: NuGet/setup-nuget@v1.0.5
    
  - uses: actions/checkout@v2
    
  - name: Setup .NET
    uses: actions/setup-dotnet@v1
    with:
      dotnet-version: 5.0.x
      
  - name: Restore dependencies
    run: dotnet restore
    
  - name: Build
    run: dotnet build --no-restore
    
  - name: Test
    run: dotnet test --no-build --verbosity normal
